language: node_js
node_js:
  - 'node'
  - 'lts/*'
cache:
  directories:
  - node_modules
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run report-coverage
branches:
  only:
  - master